data_pipeline:
  outputs:
    dev:
      account: eeqlvrw-ea85759
      database: dbt_db
      password: PsykKev2016
      role: dbt_role
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: peranderspatriksson
      warehouse: dbt_wh
  target: dev